[tool.poetry]
name = "dash-router-examples"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
dash-mantine-components = "1.0.0rc1"
dash-iconify = "^0.1.2"
dash-router = {path = "/Users/cgiessel/Documents/projects/dash-projects/dash-router/dist/dash_router-0.1.0b1.tar.gz"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
